sequenceDiagram
    participant Payhub_Be
    participant IONotification
    participant IONotification_DB
    participant Backend_IO

    Payhub_Be ->> IONotification: richiesta creazione servizio <br/>POST /create/service/{enteId}/{tipoDovutoId}
    activate IONotification
    note left of IONotification: Payhub invia payload per la <br/>creazione del servizio nella request
    IONotification ->> IONotification_DB: salva richiesta createService (se non esiste)

    alt esiste db
        IONotification ->> Backend_IO: getAll services da IO <br/>GET /manage/services
        activate Backend_IO

        alt chiamata IO fallita
            Backend_IO -->> IONotification: error
            IONotification -->> Payhub_Be: retry
        end

        Backend_IO -->> IONotification: lista di servizi
        deactivate Backend_IO

        alt servizio esiste su IO
            IONotification ->> IONotification_DB: aggiorna servizio <br/>(serviceId, stato)
            IONotification -->> Payhub_Be: 201 CREATED
        else servizio NON esiste su IO
            IONotification ->> Backend_IO: creare sevizio <br/>POST /api/v1/manage/services
            activate Backend_IO

            alt chiamata IO fallita
                Backend_IO -->> IONotification: error
                IONotification -->> Payhub_Be: retry
            end

            Backend_IO -->> IONotification: servizio
            deactivate Backend_IO
            IONotification ->> IONotification_DB: aggiorna servizio <br/>(serviceId, stato)
            IONotification -->> Payhub_Be: 201 CREATED
        end

    else NON esiste db
        IONotification ->> Backend_IO: creare sevizio <br/>POST /api/v1/manage/services
        activate Backend_IO

        alt chiamata IO fallita
            Backend_IO -->> IONotification: error
            IONotification -->> Payhub_Be: retry
        end

        Backend_IO -->> IONotification: servizio
        deactivate Backend_IO
        IONotification ->> IONotification_DB: aggiorna servizio <br/>(serviceId, stato)
        IONotification -->> Payhub_Be: 201 CREATED

    else error
        IONotification_DB -->> IONotification: 429
        IONotification -->> Payhub_Be: retry
    end

    deactivate IONotification
