---
title: WF recupero data di notifica di SEND
---
flowchart TD
    DESCRIPTION@{ shape: braces, label: "Input: sendNotificationId" }
    START@{shape: start} -->
    RETRIEVE_NOTIFICATION_DATE_ACTIVITY -->
    IS_SUCCESS{"Return true?"} -->
    |No|RESCHEDULE_WF:::activity@{label: "Rischedula se stesso"} -->
    END@{shape: stop}

    IS_SUCCESS -->
    |Sì|PUBLISH_EVENT_LOOP -->
    END

    subgraph PUBLISH_EVENT_LOOP["Per ogni DebtPosition"]
        PUBLISH_EVENT:::activity@{label: "Pubblica evento su coda"}
    end
    class PUBLISH_EVENT_LOOP loop

    subgraph RETRIEVE_NOTIFICATION_DATE_ACTIVITY["Recupero e salvataggio data di notifica"]
        RETRIEVE_NOTIFICATION_DATE["Invoca API di p4pa-send-notification per recuperare data di notifica"] -->
        IS_NOTIFIED{"Data di notifica presente?"} -->
        |No|RETURN_KO@{shape: terminal, label: "Return null"}

        subgraph SAVE_NOTIFICATION_DATE_NOTE_BLOCK
            SAVE_NOTIFICATION_DATE
            SAVE_NOTIFICATION_DATE_NOTE@{shape: braces, label: "Comporterà l'invocazione dell'API syncDebtPosition di workflow-hub"}
            SAVE_NOTIFICATION_DATE_NOTE_2@{shape: braces, label: "In caso di WF multe, qualora la Posizione Debitoria risulta ancora non pagata, ciò comporterà l'attivazione della scadenza del periodo di riduzione"}
        end
        class SAVE_NOTIFICATION_DATE_NOTE_BLOCK disable

        IS_NOTIFIED -->
        |Sì|SAVE_NOTIFICATION_DATE["Invoca API installmentSynchronize di debt-positions per salvare data di notifica"] -->
        RETURN_OK@{shape: terminal, label: "Return SendNotification"}

        subgraph RETRIEVE_NOTIFICATION_DATE_NOTE_BLOCK
            RETRIEVE_NOTIFICATION_DATE
            RETRIEVE_NOTIFICATION_DATE_NOTE@{shape: braces, label: "L'API verifica se la data è già salvata ed eventualmente la restituisce, altrimenti invoca l'API di SEND per richiederla ed eventualmente salvarla"}
        end
        class RETRIEVE_NOTIFICATION_DATE_NOTE_BLOCK disable
    end
    class NOTIFICATION_DATE_RETRIEVE activity


    classDef disable display:none;
    classDef activity fill:#FFFFE0, stroke:#ffc300, stroke-width:2px;
    classDef loop fill:#CCFFCC, stroke:#7FBF7F, stroke-width:2px, padding-bottom: 5px;