openapi: 3.0.1
info:
  title: p4pa-cie
  description: Api and Models
  version: 0.0.1
servers:
  - url: "http://localhost:8080"
    description: Generated server url
tags:
  - name: mint
    description: "Api for Ministero degli Interni"
paths:
  /debt-position:
    post:
      tags:
        - DebtPositionCie
      operationId: createDebtPositionCie
      security:
        - BearerAuth: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DebtPositionCieRequestDTO"
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: 'DebtPositionDTO'
        "400":
          description: Invalid request
        "401":
          description: Unauthorized - Missing or invalid token
        "500":
          description: Internal Server Error
  /debt-position/paid:
    post:
      tags:
        - DebtPositionCie
      operationId: notifyDebtPositionCiePayment
      security:
        - BearerAuth: [ ]
      requestBody:
        content:
          application/json:
            schema:
              type: "DebtPositionDTO"
        required: true
      responses:
        "200":
          description: Ok
        "400":
          description: Invalid request
        "401":
          description: Unauthorized - Missing or invalid token
        "500":
          description: Internal Server Error
  /public/organizations:
    get:
      tags:
        - OrganizationCie
      operationId: getOrganizations
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DynamicLabelDTO"
        "500":
          description: Internal Server Error
  /public/organizations/{orgFiscalCode}/amount:
    get:
      tags:
        - OrganizationCie
      operationId: getAmountByOrgFiscalCodeAndDebtPositionTypeOrgCode
      parameters:
        - name: orgFiscalCode
          in: path
          required: true
          schema:
            type: string
        - name: debtPositionTypeOrgCode
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CurrencyDTO"
        "400":
          description: Invalid request
        "401":
          description: Unauthorized - Missing or invalid token
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
  /mint/payments:
    get:
      tags:
        - mintCie
      summary: "Retrieve a paged list of CIE payments"
      operationId: mintGetPayments
      security:
        - BearerAuth: [ ]
      parameters:
        - name: orgFiscalCode
          in: query
          schema:
            type: string
        - name: completionDateFrom
          in: query
          schema:
            type: string
            format: date-time
        - name: completionDateTo
          in: query
          schema:
            type: string
            format: date-time
        - name: paymentDateFrom
          in: query
          schema:
            type: string
            format: date-time
        - name: paymentDateTo
          in: query
          schema:
            type: string
            format: date-time
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PagedPaymentCieDTO"
        "400":
          description: Invalid request
        "401":
          description: Unauthorized - Missing or invalid token
        "500":
          description: Internal Server Error
      x-spring-paginated: true
  /ipzs/notice:
    get:
      tags:
        - ipzsCie
      operationId: ipzsGetNoticeByNavAndOrgFiscalCode
      security:
        - BearerAuth: [ ]
      parameters:
        - name: nav
          in: query
          required: true
          schema:
            type: string
        - name: orgFiscalCode
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NoticeCieDTO"
        "400":
          description: Invalid request
        "401":
          description: Unauthorized - Missing or invalid token
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
  /ipzs/notices:
    get:
      tags:
        - ipzsCie
      operationId: ipzsGetNotices
      security:
        - BearerAuth: [ ]
      parameters:
        - name: debtorFiscalCode
          in: query
          required: true
          schema:
            type: string
        - name: orgFiscalCode
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PagedNoticeCieDTO"
        "400":
          description: Invalid request
        "401":
          description: Unauthorized - Missing or invalid token
        "500":
          description: Internal Server Error
      x-spring-paginated: true
  /ipzs/{orgFiscalCode}/notices/{nav}/setStatus:
    post:
      tags:
        - ipzsCie
      operationId: ipzsUpdateNoticeStatus
      security:
        - BearerAuth: [ ]
      parameters:
        - name: orgFiscalCode
          in: path
          required: true
          schema:
            type: string
        - name: nav
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - status
              properties:
                status:
                  type: string
                  enum:
                    - BURN
                    - REFUND
                operationDate:
                  type: string
                  format: date-time
                  example: 2025-01-01T00:00:00
        required: true
      responses:
        "200":
          description: Ok
        "400":
          description: Invalid request
        "401":
          description: Unauthorized - Missing or invalid token
        "404":
          description: Not Found
        "409":
          description: Conflict
        "500":
          description: Internal Server Error
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    ErrorDTO:
      type: object
      required:
        - category
        - message
      properties:
        category:
          type: string
          enum:
            - NOT_FOUND
            - BAD_REQUEST
            - GENERIC_ERROR
            - CONFLICT
        message:
          type: string
        traceId:
          type: string
        code:
          type: string
    DebtPositionCieStatus:
      type: string
      enum:
        - UNPAID
        - PAID
        - BURNED
        - REFUNDED
    PagedPaymentCieDTO:
      type: object
      required:
        - content
        - size
        - totalElements
        - totalPages
        - number
      properties:
        content:
          type: array
          items:
            $ref: "#/components/schemas/PaymentCieDTO"
        size:
          type: integer
          format: int64
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int64
        number:
          type: integer
          format: int64
    PaymentCieDTO:
      type: object
      required:
        - status
        - nav
        - reasonCode
        - reasonDescription
        - orgFiscalCode
        - orgName
        - orgAmountCents
        - mefAmountCents
      properties:
        status:
          $ref: "#/components/schemas/DebtPositionCieStatus"
          description: "Payment status"
        paymentDate:
          type: string
          format: date-time
          description: "Payment date and time"
        completionDate:
          type: string
          format: date-time
          description: "Date and time when the payment was consumed for the CIE issuance"
        nav:
          type: string
          description: "Unique payment identifier"
        reasonCode:
          type: string
          description: "Reason code"
        reasonDescription:
          type: string
          description: "Reason description"
        orgFiscalCode:
          type: string
          description: "Organization fiscal code"
        orgName:
          type: string
          description: "Organization name"
        orgAmountCents:
          type: integer
          format: int64
          description: "Amount due to the organization"
        mefAmountCents:
          type: integer
          format: int64
          description: "Amount due to MEF"
    DebtPositionCieRequestDTO:
      type: object
      required:
        - origin
        - debtor
        - debtPositionTypeOrgCode
        - orgFiscalCode
        - remittanceInformation
      properties:
        origin:
          $ref: "#/components/schemas/DebtPositionCieOriginAllowedEnum"
        debtor:
          type: PersonDTO
        debtPositionTypeOrgCode:
          type: string
        payer:
          type: PersonDTO
        orgFiscalCode:
          type: string
        remittanceInformation:
          type: string
    DebtPositionCieOriginAllowedEnum:
      type: string
      enum:
        - SPONTANEOUS
        - SPONTANEOUS_PSP
    CurrencyDTO:
      type: object
      required:
        - result
      properties:
        result:
          description: 'result amount in cents'
          type: integer
          format: int64
    NoticeCieDTO:
      type: object
      required:
        - status
        - nav
        - reasonCode
        - orgAmountCents
        - mefAmountCents
      properties:
        status:
          $ref: "#/components/schemas/DebtPositionCieStatus"
        paymentDate:
          type: string
          format: date-time
        burnDate:
          type: string
          format: date-time
        nav:
          type: string
        reasonCode:
          type: string
        orgAmountCents:
          type: integer
          format: int64
        mefAmountCents:
          type: integer
          format: int64
    PagedNoticeCieDTO:
      type: object
      required:
        - content
        - size
        - totalElements
        - totalPages
        - number
      properties:
        content:
          type: array
          items:
            $ref: "#/components/schemas/NoticeCieDTO"
        size:
          type: integer
          format: int64
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int64
        number:
          type: integer
          format: int64
    DynamicLabelDTO:
      type: object
      required:
        - result
      properties:
        result:
          type: array
          items:
            $ref: "#/components/schemas/LabelDTO"
    LabelDTO:
      type: object
      required:
        - label
        - value
      properties:
        label:
          type: string
        value:
          type: string
