---
title: ER - Piattaforma Unitaria
---
erDiagram
    mygov_utente {
        Long mygov_utente_id
        String cod_fed_user_id
        String cod_user_code
        String de_fed_legal_entity
        Integer version
        Date dt_ultimo_login
    }

    mygov_operatore {
        Long mygov_operatore_id
        Long mygov_utente_id
        String cod_fed_user_id
        String ruolo
        String cod_ipa_ente
    }

    mygov_ente {
        Long mygov_ente_id
        String cod_ipa_ente
        String codice_fiscale_ente
        String de_nome_ente
    }

    mygov_operatore_ente_tipo_dovuto{
        Long mygov_operatore_ente_tipo_dovuto_id
        long mygov_operatore_id
        Long mygov_ente_tipo_dovuto_id
        bool flg_attivo
    }

    mygov_import_dovuti {
        Long mygov_import_dovuti_id
        Long mygov_ente_id
        Long mygov_utente_id
    }

    mygov_export_dovuti {
        Long mygov_export_dovuti_id
        Long mygov_utente_id
        Long mygov_ente_id
        Date dt_inizio_estrazione
        String de_nome_file_generato
        String cod_tipo_dovuto
    }

    mygov_utente ||--o{ mygov_operatore : is
    mygov_operatore ||--o{ mygov_operatore_ente_tipo_dovuto: allowed
    mygov_operatore }o--|| mygov_ente: belongs
    mygov_utente ||--o{ mygov_import_dovuti : submits
    mygov_utente ||--o{ mygov_export_dovuti : requests
