sequenceDiagram
    actor Operatore
    participant UserAgent
    participant FE as FE_MyOperatore
    participant BFF as BFF_MyOperatore
    participant AUTH as P4PA_AUTH
    participant IAM

    activate UserAgent
        alt Operatore entra direttamente sul portale Piattaforma Unitaria
            note over Operatore, UserAgent: Assenza di una sessione valida
            Operatore ->> UserAgent: Accede al portale Piattaforma Unitaria

            UserAgent ->> FE: #
            activate FE
                FE -->> UserAgent: Redirect verso pagina di login
            deactivate FE
        else
            Operatore ->> UserAgent: Accede al portale SelfCare
        end

        UserAgent ->> IAM: Pagina di login
        activate IAM
            note right of IAM: L'utente si autentica e accede<br />al prodotto "Piattaforma Unitaria"
            IAM -->> UserAgent: Redirect verso pagina di accettazione ID Token
        deactivate IAM
        note over UserAgent, IAM: RFC 8693 dello standard OAuth 2.0, token passato mediante query param.<BR />L'ID Token dovrà avere durata effimera (1 minuto)

        UserAgent ->> FE: Prosegue con la redirect
        activate FE
            FE ->> BFF: Consegna ID Token
            activate BFF
                BFF ->> AUTH: POST /token
                activate AUTH
                    AUTH ->> IAM: Recupera .well-known/jwks.json
                    note right of AUTH: Valida ID Token
                    note right of AUTH: Genera access Token (exp 4 ore)
                    note right of AUTH: Salva in cache la coppia<BR />AccessToken.jti: ID Token<BR />Retention pari al exp
                    AUTH ->> BFF: Consegna access Token
                deactivate AUTH

                BFF ->> AUTH: GET /userinfo
                activate AUTH
                    note right of AUTH: Recupera l'ID Token dalla cache
                    AUTH -->> BFF: Dati utente ed ente di accesso
                deactivate AUTH

                BFF ->> BFF: Registra dati utente (no PII)

                BFF -->> FE: access token JWT
            deactivate BFF

            FE ->> BFF: GET /userinfo
            activate BFF
                BFF ->> AUTH: GET /userinfo
                activate AUTH
                    note right of AUTH: Recupera l'ID Token dalla cache
                    AUTH -->> BFF: Dati utente ed ente di accesso
                deactivate AUTH
            BFF -->> FE: Dati utente
            deactivate BFF
            note right of FE: Salva dati utente in memoria

            note right of UserAgent: token di sessione persistito nel session storage
            FE -->> UserAgent: #
        deactivate FE

        UserAgent -->> Operatore: #
    deactivate UserAgent

    note right of Operatore: Operatore libero di navigare<BR />all'interno del portale