---
title: Caricamento di un file da importare
---
sequenceDiagram
    actor CLIENT as SIL/FE
    participant MS_FILESHARE as p4pa-file-share
    participant MS_PROCESS_EXECUTIONS as p4pa-process-executions
    participant MS_WF as p4pa-workflow-hub
    participant WF as Temporal
    participant SHARED as Shared Folder
    participant MS_AUTH as p4pa-auth
    participant MS_ENTITY as Microservizio entità

    CLIENT ->>+ MS_FILESHARE: POST file + jwt
        MS_FILESHARE ->> MS_AUTH: getUserInfo()
        MS_FILESHARE ->> MS_FILESHARE: Autorizza la chiamata<BR />Cifra il file
        MS_FILESHARE ->> SHARED: Deposita file cifrato
        MS_FILESHARE ->>+ MS_PROCESS_EXECUTIONS: createIngestionFlowFile()
            MS_PROCESS_EXECUTIONS ->> MS_PROCESS_EXECUTIONS: Crea entità ingestion_flow_file<BR />Status=UPLOADED
            MS_PROCESS_EXECUTIONS ->>+ MS_WF: Richiesta avvio WF
                MS_WF ->> MS_WF: Determina il WF da invocare
                MS_WF ->>+ WF: Avvia WF
                MS_WF -->>- MS_PROCESS_EXECUTIONS: workflowId
            MS_PROCESS_EXECUTIONS -->>- MS_FILESHARE: ingestionFlowFileId
        MS_FILESHARE -->>- CLIENT: ingestionFlowFileId

    WF ->> MS_PROCESS_EXECUTIONS: Aggiorna stato ingestion_flow_file in<BR />PROCESSING
    WF ->> SHARED: Recupero file
    WF ->> WF: Decifratura file
    WF ->> MS_ENTITY: saveAll()
    WF ->> SHARED: Archiviazione file
    WF ->> MS_PROCESS_EXECUTIONS: Aggiorna stato ingestion_flow_file in<BR />COMPLETED
    WF ->> MS_AUTH: getUserInfoFromMappedExternaUserId()
    WF ->> CLIENT: Notifica esito operazione tramite email
    opt Il WF di caricamento fa parte di una catena di WF
        WF ->>+ WF: Avvia WF successivo
        WF ->> WF: Elaborazione
        deactivate WF
    end
    deactivate WF
