---
title: WF caricamento file Tesoreria
---
flowchart TD
    DESCRIPTION@{ shape: braces, label: "Input: path del file da caricare" }
    START@{shape: start} --> INJESTION:::activity@{label: "Leggi file e persisti righe"}

    INJESTION --> LOOP

    subgraph LOOP["Per ogni IUF restituito dall'activity di injestion"]

        %% dummy block added to have an empty line
        DUMMY:::disable-->SIGNAL
        linkStyle 2 display:none;

        SIGNAL:::activity@{label: "Invia evento 'Tesoreria' al workflow Riconciliazione"}
        NOTE@{ shape: braces, label: "signalWithStart con workflowID=IUF" }
    end

    LOOP --> END@{shape: stop}
    class LOOP loop

    classDef disable display:none;
    classDef activity fill:#FFE5B4, stroke:#FFB347, stroke-width:2px;
    classDef loop fill:#CCFFCC, stroke:#7FBF7F, stroke-width:2px, padding-bottom: 5px;