openapi: 3.0.1
info:
  title: p4pa-migration
  description: Api and Models
  version: 0.0.1
servers:
  - url: http://localhost:8080
paths:
  /migration/organization/{orgIpaCode}/{migrationFileType}:
    post:
      tags:
        - migration-file
      summary: uploadMigrationFlowFile
      description: Service to store an migration file
      operationId: uploadMigrationFile
      parameters:
        - name: orgIpaCode
          in: path
          required: true
          schema:
            type: string
        - name: migrationFileType
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/MigrationFileTypeEnum'
      requestBody:
        content:
          'multipart/form-data':
            schema:
              required:
                - migrationFile
              type: object
              properties:
                migrationFile:
                  type: string
                  format: binary
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadMigrationFileResponseDTO'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /migration/organization/{orgIpaCode}:
    get:
      tags:
        - migration-file
      summary: getMigrationFlows
      description: Service to retrieve upload request statuses
      operationId: getMigrationUploads
      parameters:
        - name: orgIpaCode
          in: path
          required: true
          schema:
            type: string
        - name: migrationFileType
          in: query
#          required: true
          schema:
            $ref: '#/components/schemas/MigrationFileTypeEnum'
        - name: status
          in: query
          required: false
          schema:
            type: 'UploadsStatusEnum'
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                type: array
                items:
                  type: 'Uploads'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /migration/organization/{orgIpaCode}/migrations/{uploadId}:
    get:
      tags:
        - migration-file
      summary: getMigrationFlow
      description: Service to retrieve an upload request
      operationId: getMigrationUpload
      parameters:
        - name: orgIpaCode
          in: path
          required: true
          schema:
            type: string
        - name: uploadId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                type: 'Uploads'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /migration/organization/{orgIpaCode}/migrations/{uploadId}/details:
    get:
      tags:
        - migration-file
      summary: getMigrationFlowDetails
      description: Service to retrieve upload request details
      operationId: getMigrationUploadDetails
      parameters:
        - name: orgIpaCode
          in: path
          required: true
          schema:
            type: string
        - name: uploadId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                type: array
                items:
                  type: 'UploadDetails'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /migration/organization/{orgIpaCode}/migrations/{uploadId}/details/{uploadDetailsId}:
    get:
      tags:
        - migration-file
      summary: getMigrationFlowDetail
      description: Service to retrieve upload request detail
      operationId: getMigrationUploadDetail
      parameters:
        - name: orgIpaCode
          in: path
          required: true
          schema:
            type: string
        - name: uploadId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: uploadDetailsId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                type: 'UploadDetails'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /migration/organization/{orgIpaCode}/migrations/{uploadId}/errors:
    get:
      tags:
        - migration-file
      summary: getMigrationErrors
      description: Service to retrieve errors on an upload request
      operationId: getMigrationErrors
      parameters:
        - name: orgIpaCode
          in: path
          required: true
          schema:
            type: string
        - name: uploadId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: ZIP file containing error files
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '204':
          description: No Content - No Errors Found
        '401':
          description: Unauthorized - Missing or invalid token
        '403':
          description: Forbidden - No upload in error state
        '404':
          description: Not Found - Upload not found
        '500':
          description: Internal Server Error - Error during errors processing
  /internal/workflows/{workflowId}/status:
    get:
      tags:
        - Workflow
      operationId: getWorkflowStatus
      summary: Get Workflow Status
      description: Retrieve the current status of a Temporal workflow by its ID.
      parameters:
        - name: workflowId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "Workflow status retrieved successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowStatusDTO'
        '404':
          description: "Workflow not found"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
security:
  - BearerAuth: [ ]
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    MigrationFileTypeEnum:
      type: string
      enum:
        - ORGANIZATIONS
        - ORG_SIL_SERVICES
        - DEBT_POSITIONS_TYPE
        - DEBT_POSITIONS_TYPE_ORG
        - DEBT_POSITIONS_TYPE_ORG_OPERATORS
        - PAYMENT_NOTIFICATION
        - PAYMENTS_REPORTING
        - TREASURY_CSV_COMPLETE
        - ASSESSMENTS
        - ASSESSMENTS_REGISTRY
        - DEBT_POSITIONS
        - DEBT_POSITIONS_PAID
    UploadMigrationFileResponseDTO:
      type: object
      required:
        - uploadId
        - workflowId
        - runId
      properties:
        uploadId:
          type: integer
          format: int64
        workflowId:
          type: string
        runId:
          type: string
    WorkflowCreatedDTO:
      type: object
      required:
        - workflowId
        - runId
      properties:
        workflowId:
          type: string
        runId:
          type: string
    WorkflowStatusDTO:
      type: object
      required:
        - workflowId
        - workflowType
        - status
        - runId
        - taskQueue
      properties:
        workflowId:
          type: string
        workflowType:
          type: string
        status:
          type: string
        runId:
          type: string
        taskQueue:
          type: string
        startDateTime:
          type: string
          format: date-time
        executionDateTime:
          type: string
          format: date-time
        endDateTime:
          type: string
          format: date-time
        duration:
          type: string
          format: duration
    ErrorDTO:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          enum:
            - NOT_FOUND
            - BAD_REQUEST
            - GENERIC_ERROR
            - FILE_UPLOAD_ERROR
            - INVALID_FILE
            - FORBIDDEN
        message:
          type: string
        traceId:
          type: string
