openapi: 3.1.0
info:
  title: p4pa-send-bff
  description: Api and Models
  version: 1.0.0
paths:
  /organizations/{organizationId}/senders:
    get:
      tags:
        - organization-sender
      operationId: getOrganizationSenders
      summary: "Returns the list of SEND-enabled organization and sub-units accessible to the operator"
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrganizationSenderDTO'
        '401':
          description: Unauthorized - Missing or invalid token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /organizations/{organizationId}/campaigns:
    get:
      tags:
        - Campaign
      operationId: getCampaignsByFilters
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: dateFrom
          in: query
          schema:
            type: string
            format: date
        - name: dateTo
          in: query
          schema:
            type: string
            format: date
        - name: orgSubUnitCode
          in: query
          schema:
            type: string
        - name: campaignName
          in: query
          schema:
            type: string
        - name: externalCampaignId
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Page of campaigns
          content:
            application/json:
              schema:
                type: 'PagedCampaign'
        '400':
          description: Invalid request
        '401':
          description: Unauthorized - Missing or invalid token
        '500':
          description: Internal Server Error
      x-spring-paginated: true
  /organizations/{organizationId}/campaigns/{campaignId}/name:
    patch:
      summary: Rename campaign
      tags:
        - Campaign
      operationId: renameCampaign
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: campaignId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: 'RenameCampaignRequest'
      responses:
        '200':
          description: OK
        '403':
          description: Forbidden
        '404':
          description: Campaign not found
        '500':
          description: Internal Server Error
  /organizations/{organizationId}/campaigns/{campaignId}:
    get:
      tags:
        - Campaign
      operationId: getCampaign
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: campaignId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                type: 'Campaign'
        '400':
          description: Invalid request
        '401':
          description: Unauthorized - Missing or invalid token
        '404':
          description: Campaign not found
        '500':
          description: Internal Server Error
  /organizations/{organizationId}/campaigns/{campaignId}/notifications:
    get:
      tags:
        - Campaign
      operationId: getCampaignSendNotifications
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: campaignId
          in: path
          required: true
          schema:
            type: string
        - name: iun
          in: query
          schema:
            type: string
        - name: dateFrom
          in: query
          schema:
            type: string
            format: date-time
        - name: dateTo
          in: query
          schema:
            type: string
            format: date-time
        - name: status
          in: query
          schema:
            $ref: '#/components/schemas/SendNotificationStatus'
        - name: fiscalCode
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Page of Notifications
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedSendNotifications'
        "400":
          description: Invalid request
        '500':
          description: Internal Server Error
      x-spring-paginated: true
  /organizations/{organizationId}/campaigns/{campaignId}/notifications/{notificationId}:
    get:
      tags:
        - SendNotification
      operationId: getNotificationDetails
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: campaignId
          in: path
          required: true
          schema:
            type: string
        - name: notificationId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                type: 'SendNotificationExtendedDTO'
        '400':
          description: Invalid request
        '401':
          description: Unauthorized - Missing or invalid token
        '404':
          description: Campaign not found
        '500':
          description: Internal Server Error
components:
  schemas:
    OrganizationSenderDTO:
      type: object
      required:
        - organizationId
      properties:
        organizationId:
          type: integer
          format: int64
        subUnitCode:
          type: string
        orgName:
          type: string
    ErrorDTO:
      type: object
      required:
        - category
        - code
        - message
      properties:
        category:
          type: string
          enum:
            - NOT_FOUND
            - BAD_REQUEST
            - GENERIC_ERROR
            - TOO_MANY_REQUESTS
            - CONFLICT
            - FORBIDDEN
            - UNAUTHORIZED
        code:
          type: string
        message:
          type: string
        traceId:
          type: string
    PagedSendNotifications:
      type: object
      required:
        - content
        - size
        - totalElements
        - totalPages
        - number
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/SendNotification'
        size:
          type: integer
          format: int64
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int64
        number:
          type: integer
          format: int64
    SendNotificationStatus:
      type: string
      description: The status of the Send Notification
      enum:
        - COMPLETED
        - IN_PROGRESS
        - CANCELLED
        - REFUSED
        - UNSUCCESSFUL
    SendNotification:
      type: object
      required:
        - sendNotificationId
        - creationDate
      properties:
        sendNotificationId:
          type: string
        creationDate:
          type: string
          format: date-time
        iun:
          type: string
        status:
          $ref: '#/components/schemas/SendNotificationStatus'

