sequenceDiagram
actor A as Administrator
alt Amministratore non abilitato
A->>+UserAgent: Accede al portale piattaforma unitaria
UserAgent->>+P4PA-AUTH: POST /register
P4PA-AUTH->>P4PA-AUTH: verifica autorizzazioni
note right of P4PA-AUTH: Verifica se l'amministratore ha le <br/>autorizzazioni per quell'ente
P4PA-AUTH-->>-UserAgent: 403 utente non autorizzato
else Amministratore abilitato
opt crezione ente
UserAgent->>P4PA-BE: creazione ente
note right of P4PA-BE: creazione ente <br/> avvenuta con successo
P4PA-BE->>+P4PA-AUTH: POST /register
P4PA-AUTH->>P4PA-AUTH: creazione del client_secret
P4PA-AUTH->>P4PA-AUTH: cifratura client_secret
P4PA-AUTH-->>-P4PA-BE: 200 ok
P4PA-BE-->>UserAgent: 200 ok
end
opt creazone client manuale
UserAgent->>+P4PA-AUTH: POST /register
P4PA-AUTH->>P4PA-AUTH: verifica autorizzazioni
P4PA-AUTH->>P4PA-AUTH: creazione del client_secret
P4PA-AUTH->>P4PA-AUTH: cifratura client_secret
P4PA-AUTH-->>-UserAgent: 200 response
end
UserAgent-->>-A: 
end