---
title: WF caricamento file Ricevute
---
flowchart TD
    DESCRIPTION@{ shape: braces, label: "Input: ingestionFlowId" }
    START@{shape: start} -->
    UPDATE_STATUS_INELAB:::activity@{label: "Aggiorna stato ingestionFlowFile in 'PROCESSING'"} -->
    INGESTION:::activity@{label: "Leggi file,<BR />invoca API createReceipt di p4pa-debt-position,<BR />archivia il file"} -->
    UPDATE_STATUS_COMPLETE:::activity@{label: "Finalizza stato entità ingestionFlowId"} -->
    SEND_EMAIL:::activity@{label: "Notifica stato import tramite email"} -->
    END@{shape: stop}

    subgraph INGESTION_NOTE_BLOCK
        INGESTION
        INGESTION_NOTE@{shape: braces, label: "p4pa-debt-positions invierà la notifica verso KAFKA"}
    end
    class INGESTION_NOTE_BLOCK disable

    classDef disable display:none;
    classDef activity fill:#FFFFE0, stroke:#ffc300, stroke-width:2px;
    classDef loop fill:#CCFFCC, stroke:#7FBF7F, stroke-width:2px, padding-bottom: 5px;