---
title: WF classifica rata pagata
---
flowchart TD
    DESCRIPTION@{ shape: braces, label: "Input: IUV pagato" }
    START@{shape: start} --> CLASSIFY_DUPLICATE:::activity@{label: "Verifica e classifica se doppione"}

    CLASSIFY_DUPLICATE -->SIGNAL

    subgraph SIGNAL_NOTE_BLOCK
        SIGNAL:::send-signal@{shape: delay, label: "Invia evento 'Classifica IUD' al workflow 'Classificazione IUD'"}
        SIGNAL_NOTE@{ shape: braces, label: "signalWithStart con workflowID=IUD" }
    end
    class SIGNAL_NOTE_BLOCK note_block

    SIGNAL --> END@{shape: stop}

    classDef note_block display:none;
    classDef activity fill:#FFFFE0, stroke:#ffc300, stroke-width:2px;
    classDef send-signal fill:#ade8f4, stroke:#48cae4, stroke-width:2px