---
title: WF caricamento file Ricevute
---
flowchart TD
    DESCRIPTION@{ shape: braces, label: "Input: ingestionFlowId" }
    START@{shape: start} -->
    UPDATE_STATUS_INELAB:::activity@{label: "Aggiorna stato ingestionFlow in 'IMPORT_IN_ELAB'"} -->
    INGESTION:::activity@{label: "Leggi file e persisti righe"} -->
    UPDATE_STATUS_COMPLETE:::activity@{label: "Finalizza stato entità ingestionFlowId"} -->
    SEND_EMAIL:::activity@{label: "Notifica stato import tramite email"} -->

    LOOP

    subgraph LOOP["Per ogni coppia di IUV e IUD restituiti dall'activity di ingestion"]

        %% dummy block added to have an empty line
        DUMMY:::disable-->SIGNAL
        linkStyle 5 display:none;

        SIGNAL:::send-signal@{shape: delay, label: "Invia evento 'Ricevuta' al workflow 'Classificazione IUD'"}
        NOTE@{ shape: braces, label: "signalWithStart con workflowID=IUD" }
    end

    LOOP --> END@{shape: stop}
    class LOOP loop

    classDef disable display:none;
    classDef activity fill:#FFFFE0, stroke:#ffc300, stroke-width:2px;
    classDef loop fill:#CCFFCC, stroke:#7FBF7F, stroke-width:2px, padding-bottom: 5px;
    classDef send-signal fill:#ade8f4, stroke:#48cae4, stroke-width:2px