---
title: WF recupero Rendicontazioni da pagoPA
---
flowchart TD
    DESCRIPTION@{ shape: braces, label: "WF schedulato periodicamente" }

    START@{shape: start} -->
    FETCH_BROKER_LIST:::activity@{label: "Recupero lista intermediari"} -->
    BROKER_LOOP

    subgraph BROKER_LOOP["Per ogni intermediario"]
        FETCH_ORG_LIST:::activity@{label: "Recupero lista enti intermediati in stato ACTIVE"} -->
        ORG_FETCH_WF_LOOP

        subgraph ORG_FETCH_WF_LOOP["Per ogni ente"]
            FETCH_FILE[["Avvia WF<BR/>'recupero Rendicontazioni ente da pagoPA'"]]

            NOTE@{ shape: braces, label: "WF eseguito async e workflowId: organizationId" }
        end
        class ORG_FETCH_WF_LOOP loop
    end
    class BROKER_LOOP loop

    BROKER_LOOP --> END@{shape: stop}

    classDef disable display:none;
    classDef activity fill:#FFFFE0, stroke:#ffc300, stroke-width:2px;
    classDef loop fill:#CCFFCC, stroke:#7FBF7F, stroke-width:2px, padding-bottom: 5px;
