---
title: WF recupero Rendicontazioni da pagoPA
---
flowchart TD
    DESCRIPTION@{ shape: braces, label: "WF schedulato periodicamente" }

    START@{shape: start} -->
    FETCH_LIST:::activity@{label: "Chiedi flussi di Rendicontazione non elaborati"} -->
    LOOP

    subgraph FETCH_LIST_NOTE_BLOCK
        FETCH_LIST
        FETCH_FILE_NOTE@{shape: braces, label: "Si appoggerà alla tabella ingestion_flow_file per determinare i flussi già ottenuti per l'ente"}
    end
    class FETCH_LIST_NOTE_BLOCK disable

    subgraph LOOP["Per ogni flusso ottenuto"]
        FETCH_FILE:::activity@{label: "Chiedi file di Rendicontazione"}

        NOTE@{ shape: braces, label: "p4pa-pagopa-payments recupererà il singolo file e demanderà a<BR />p4pa-file-share il suo caricamento" }
    end

    LOOP --> END@{shape: stop}
    class LOOP loop

    classDef disable display:none;
    classDef activity fill:#FFFFE0, stroke:#ffc300, stroke-width:2px;
    classDef loop fill:#CCFFCC, stroke:#7FBF7F, stroke-width:2px, padding-bottom: 5px;
