---
title: Flusso Rendicontazione
---
sequenceDiagram
    actor USER as Operatore Ente
    participant PU-FE as PiattaformaUnitaria-FE
    participant PU-BE as PiattaformaUnitaria-BE
    participant WF as Workflow Service
    participant PAGOPA as pagoPA Service
    participant FS as File Share Service

    alt Caricamento manuale
        note over PU-FE: Pagina flussi di Rendicontazione
        USER ->> PU-FE: Carica file Rendicontazione

        activate PU-FE
            PU-FE ->> PU-BE: #

            activate PU-BE
                PU-BE ->>+ FS: Salva file Rendicontazione
                    FS ->>+ WF: Avvia Rendicontazione
                        WF ->>WF: Avvia async<BR />"WF caricamento file Rendicontazione"
                        WF -->>- FS: #
                    FS -->>- PU-BE: #

                PU-BE -->> PU-FE: #
            deactivate PU-BE

            PU-FE -->> USER: #
        deactivate PU-FE
    else Schedulazione automatica
        rect rgba(0, 0, 255, .1)
            note over WF: "WF recupero Rendicontazione da pagoPA"
            WF ->>+ WF : Schedulazione periodica
                WF ->>+ PAGOPA: Chiedi lista flussi
                PAGOPA -->>- WF: Lista flussi

                loop Per ogni flusso di Rendicontazione
                    WF ->>+ PAGOPA: Chiedi file flusso Rendicontazione
                        PAGOPA ->>+ FS: Salva file Rendicontazione
                        PAGOPA -->>- WF: #
                    deactivate WF

                    FS ->> WF : Avvia async<BR />"WF caricamento file Rendicontazione"
                    deactivate FS
                end
        end

    end