---
title: WF caricamento giornale di cassa XLS
---
flowchart TD
    DESCRIPTION@{ shape: braces, label: "Input: ingestionFlowFileId" }
    START@{shape: start} -->
    UPDATE_STATUS_INELAB:::activity@{label: "Aggiorna stato ingestionFlow in 'IMPORT_IN_ELAB'"} -->
    INGESTION:::activity@{label: "Leggi file e persisti righe"}

    subgraph INGESTION_NOTE_BLOCK
        INGESTION
        INGESTION_NOTE@{shape: braces, label: "Restituisce List&lt;IUF,treasuryId&gt;, <span style=\"color:red\">List&lt;IUV&gt;</span>"}
    end
    class INGESTION_NOTE_BLOCK note_block

    INGESTION -->
    UPDATE_STATUS_COMPLETE:::activity@{label: "Finalizza stato entità ingestionFlowId"} -->
    SEND_EMAIL:::activity@{label: "Notifica stato import tramite email"} -->
    LOOP_IUVs

    subgraph LOOP_IUVs["Per ogni IUV restituito dall'activity di ingestion"]

        %% dummy block added to have an empty line
        DUMMY1:::hidden-->SIGNAL_IUV
        linkStyle 5 display:none;

        SIGNAL_IUV:::send-signal@{shape: delay, label: "Invia evento 'Classifica Transfer' al workflow 'Classificazione Transfer'"}
        NOTE_SIGNAL_IUV@{ shape: braces, label: "signalWithStart con workflowID=organizationId+IUV" }
    end
    class LOOP_IUVs loop
    style LOOP_IUVs color:red;

    LOOP_IUVs --> LOOP_IUFs

    subgraph LOOP_IUFs["Per ogni IUF/treasuryId restituito dall'activity di ingestion"]

        %% dummy block added to have an empty line
        DUMMY2:::hidden-->SIGNAL_IUF
        linkStyle 7 display:none;

        SIGNAL_IUF:::send-signal@{shape: delay, label: "Invia evento 'Tesoreria IUF' con treasuryId al workflow 'Classificazione IUF'"}
        NOTE_SIGNAL_IUF@{ shape: braces, label: "signalWithStart con workflowID=organizationId+IUF" }
    end
    class LOOP_IUFs loop

    LOOP_IUFs --> END@{shape: stop}


    classDef hidden display:none;
    classDef note_block display:none;
    classDef activity fill:#FFFFE0, stroke:#ffc300, stroke-width:2px;
    classDef loop fill:#CCFFCC, stroke:#7FBF7F, stroke-width:2px, padding-bottom: 5px;
    classDef send-signal fill:#ade8f4, stroke:#48cae4, stroke-width:2px