---
config:
  flowchart:
    rankSpacing: 1
  theme: default
  look: classic
title: WF Classificazione IUF
---
flowchart TD
    subgraph WF_BLOCK
        subgraph NOTE_START_BLOCK
            DESCRIPTION@{ shape: braces, label: "Input: IUF, orgId, List&lt;IUV,IUR,transferIndex&gt;" }
            START@{shape: start}
        end
        class NOTE_START_BLOCK hidden

        START --> LOOP_IUVs

        subgraph LOOP_IUVs["Per ogni Transfer"]
        direction TB
            SIGNAL_IUV:::send-signal@{shape: delay, label: "Invia evento 'Classifica Transfer' al workflow 'Classificazione Transfer'"}
            NOTE_SIGNAL_IUV@{ shape: braces, label: "signalWithStart con workflowID=orgId+IUV+ IUR+transferIndex" }
        end
        class LOOP_IUVs loop

        LOOP_IUVs --> END@{shape: stop}
    end
    class WF_BLOCK hidden

    subgraph SIGNALS_BLOCK
    direction LR

        subgraph SIGNAL_RENDICONTAZIONE_BLOCK["Evento Rendicontazione"]
        direction LR
            DESCRIPTION_SIGNAL_RENDICONTAZIONE@{ shape: braces, label: "Input: orgId, IUF, codiceEsito, List&lt;IUV,IUR,transferIndex&gt;" } -->
            DUMMY1:::hidden --> DUMMY2:::hidden --> DUMMY3:::hidden --> DUMMY4:::hidden --> DUMMY5:::hidden
            linkStyle 2,3,4,5,6 display:none

            SIGNAL_RENDICONTAZIONE@{ shape: bolt } -->
            DELETE_CLASSIFY_NULL_IUV:::activity@{label: "Delete classificazione 'TES_NO_IUF_OR_IUV'"} -->
            IS_CODICEESITO9{"CodiceEsito == 8 o 9"} --> |Sì|HANDLE_CODICEESITO9
            subgraph HANDLE_CODICEESITO9["Gestisci codiceEsito 8 o 9"]
                SAVE_RT@{shape: database, label: "Salva Ricevuta"} -->
                SEND_RT_MSG@{shape: das, label: "Notifica Ricevuta"}
            end
            class HANDLE_CODICEESITO9 activity

            IS_CODICEESITO9 --> |No|ADD_RENDICONTAZIONE_IUVS

            HANDLE_CODICEESITO9 -->
            ADD_RENDICONTAZIONE_IUVS["Aggiungi IUV/IUR/transferIndex "] -->
            SIGNAL_RENDICONTAZIONE_END@{ shape: "stop" }
        end
        class SIGNAL_RENDICONTAZIONE_BLOCK signal_block

        subgraph SIGNAL_TESORERIA_BLOCK["Evento Tesoreria IUF"]
        direction LR
            DESCRIPTION_SIGNAL_TESORERIA@{ shape: braces, label: "Input: orgId, IUF, treasuryId" } -->
            DUMMY6:::hidden --> DUMMY7:::hidden --> DUMMY8:::hidden
            linkStyle 14,15,16 display:none

            SIGNAL_TESORERIA@{ shape: bolt } -->
            DELETE_TES_ANOMALY:::activity@{label: "Delete classificazione by treasuryId"} -->
            FIND_TESORERIA_IUVS_ACTIVITY

            subgraph FIND_TESORERIA_IUVS_ACTIVITY["Ricerca Transfers by IUF"]
                IS_IUF_EMPTY{"IUF presente?"} -->
                |Sì|SAVE_TES_IUF_ANOMALY@{shape: database, label: "Salva classificazione 'TES_NO_MATCH'"} -->
                RETURN_TESORERIA_IUVS

                IS_IUF_EMPTY -->
                |No|FIND_TESORERIA_IUVS["Ricerca Rendicontazione IUF"] -->
                EXISTS_RENDICONTAZIONE_TES{"Trovata Rendicontazione?"}

                EXISTS_RENDICONTAZIONE_TES -->
                |Sì|RETURN_TESORERIA_IUVS@{shape: terminal, label: "Restituisci IUV/IUR/transferIndex trovati"}

                EXISTS_RENDICONTAZIONE_TES -->
                |No|SAVE_TES_ANOMALY@{shape: database, label: "Salva classificazione 'TES_NO_IUF_OR_IUV'"} -->
                RETURN_TESORERIA_IUVS
            end
            class FIND_TESORERIA_IUVS_ACTIVITY activity

            FIND_TESORERIA_IUVS_ACTIVITY -->
            ADD_TESORERIA_IUVS["Aggiungi IUV/IUR/transferIndex "] -->
            SIGNAL_TESORERIA_END@{ shape: "stop" }
        end
        class SIGNAL_TESORERIA_BLOCK signal_block
    end
    class SIGNALS_BLOCK hidden

    classDef note_block display:none;
    classDef hidden display:none;
    classDef activity fill:#FFFFE0, stroke:#ffc300, stroke-width:2px;
    classDef loop fill:#CCFFCC, stroke:#7FBF7F, stroke-width:2px, padding-bottom: 5px;
    classDef signal_block fill:#ade8f4, stroke:#48cae4, stroke-width:2px
    classDef send-signal fill:#ade8f4, stroke:#48cae4, stroke-width:2px
