---
title: WF Classificazione IUD
config:
    flowchart:
        rankSpacing: 1
---
flowchart TD
    subgraph WF_BLOCK
        subgraph NOTE_START_BLOCK
            DESCRIPTION@{ shape: braces, label: "Input: orgId, IUV, IUR, transferIndex" }
            START@{shape: start}
        end
        class NOTE_START_BLOCK hidden

        START -->
        SIGNAL_IUV:::send-signal@{shape: delay, label: "Invia evento 'Classifica Transfer' al workflow 'Classificazione Transfer'"}

        subgraph NOTE_SIGNAL_IUV_BLOCK
            SIGNAL_IUV
            NOTE_SIGNAL_IUV@{ shape: braces, label: "signalWithStart con workflowID=orgId+IUV+ IUR+transferIndex" }
        end
        class NOTE_SIGNAL_IUV_BLOCK note_block

        SIGNAL_IUV --> END@{shape: stop}
    end
    class WF_BLOCK hidden

    subgraph SIGNALS_BLOCK
    direction LR

        subgraph SIGNAL_RT_BLOCK["Evento Ricevuta"]
        direction LR
            DESCRIPTION_SIGNAL_RT@{ shape: braces, label: "Input: orgId, IUD, IUV, IUR, transferIndex" } -->
            DUMMY1:::hidden --> DUMMY2:::hidden--> DUMMY3:::hidden
            linkStyle 2,3,4 display:none

            SIGNAL_RT@{ shape: bolt } -->
            DELETE_CLASSIFY_NULL_IUV:::activity@{label: "Delete classificazione 'IUD_NO_RT'"} -->
            ADD_RT_IUV["Aggiungi orgId/IUV/IUR/transferIndex "] -->
            SIGNAL_RT_END@{ shape: "stop" }
        end
        class SIGNAL_RT_BLOCK signal_block

        subgraph SIGNAL_RN_BLOCK["Evento Pagamento Notificato"]
        direction LR
            DESCRIPTION_SIGNAL_RN@{ shape: braces, label: "Input: organizationId, IUD, transferIndex" } -->
            DUMMY4:::hidden --> DUMMY5:::hidden --> DUMMY6:::hidden
            linkStyle 8,9,10 display:none;



            SIGNAL_RN@{ shape: bolt } --> FIND_RT_ACTIVITY

            subgraph FIND_RT_ACTIVITY["Ricerca IUV tramite IUD"]
                FIND_RT_IUD["Ricerca Ricevuta tramite IUD"] -->
                EXISTS_RT_IUD{"Trovata Ricevuta?"}

                EXISTS_RT_IUD -->|Sì|RETURN_RT_IUV@{shape: terminal, label: "Restituisci orgId/IUV/IUR/transferIndex se trovato"}

                EXISTS_RT_IUD -->
                |No|SAVE_RN_ANOMALY@{shape: database, label: "Salva classificazione 'IUD_NO_RT'"} -->
                RETURN_RT_IUV
            end
            class FIND_RT_ACTIVITY activity

            FIND_RT_ACTIVITY -->
            ADD_RN_IUV["Aggiungi orgId/IUV/IUR/transferIndex "] -->
            SIGNAL_RN_END@{ shape: "stop" }

        end
        class SIGNAL_RN_BLOCK signal_block
    end
    class SIGNALS_BLOCK hidden

    classDef note_block display:none;
    classDef hidden display:none;
    classDef activity fill:#FFFFE0, stroke:#ffc300, stroke-width:2px;
    classDef loop fill:#CCFFCC, stroke:#7FBF7F, stroke-width:2px, padding-bottom: 5px;
    classDef signal_block fill:#ade8f4, stroke:#48cae4, stroke-width:2px
    classDef send-signal fill:#ade8f4, stroke:#48cae4, stroke-width:2px