---
title: WF caricamento giornale di cassa XLS
---
flowchart TD
    DESCRIPTION@{ shape: braces, label: "Input: path del file da caricare" }
    START@{shape: start} --> INGESTION:::activity@{label: "Leggi file e persisti righe"}

    subgraph INGESTION_NOTE_BLOCK
        INGESTION
        INGESTION_NOTE@{shape: braces, label: "Restituisce lista IUF e lista IUV"}
    end
    class INGESTION_NOTE_BLOCK note_block

    INGESTION --> LOOP_IUVs

    subgraph LOOP_IUVs["Per ogni IUV restituito dall'activity di ingestion"]

        %% dummy block added to have an empty line
        DUMMY1:::hidden-->SIGNAL_IUV
        linkStyle 2 display:none;

        SIGNAL_IUV:::send-signal@{shape: delay, label: "Invia evento 'Classifica IUV' al workflow 'Classificazione IUV'"}
        NOTE_SIGNAL_IUV@{ shape: braces, label: "signalWithStart con workflowID=IUV" }
    end
    class LOOP_IUVs loop

    LOOP_IUVs --> LOOP_IUFs

    subgraph LOOP_IUFs["Per ogni IUF restituito dall'activity di ingestion"]

        %% dummy block added to have an empty line
        DUMMY2:::hidden-->SIGNAL_IUF
        linkStyle 4 display:none;

        SIGNAL_IUF:::send-signal@{shape: delay, label: "Invia evento 'Tesoreria IUF' al workflow 'Classificazione IUF'"}
        NOTE_SIGNAL_IUF@{ shape: braces, label: "signalWithStart con workflowID=IUF" }
    end
    class LOOP_IUFs loop

    LOOP_IUFs --> END@{shape: stop}


    classDef hidden display:none;
    classDef note_block display:none;
    classDef activity fill:#FFFFE0, stroke:#ffc300, stroke-width:2px;
    classDef loop fill:#CCFFCC, stroke:#7FBF7F, stroke-width:2px, padding-bottom: 5px;
    classDef send-signal fill:#48cae4, stroke:#023e8a, stroke-width:2px