sequenceDiagram
    participant User-Agent
    participant ARC
    participant OneIdentity as One Identity

    User-Agent->>ARC: Richiesta accesso all'applicazione
    ARC->>ARC: Controlla se il token di accesso è valido
    alt Token Valido
        ARC->>User-Agent: Accesso consentito
    else Token Non Valido
        ARC->>OneIdentity: Richiesta di autenticazione
        OneIdentity->>OneIdentity: Esegue autenticazione (stateless)
        OneIdentity->>ARC: Autenticazione riuscita
        ARC->>ARC: Genera un nuovo token di accesso
        ARC->>User-Agent: Accesso consentito con nuovo token
    end