sequenceDiagram
    actor User-Agent
    participant ARC
    participant OneIdentity


    User-Agent ->>+ ARC: GET /login
    opt 302 Redirect
        ARC ->>+ User-Agent: return redirect to Login page
        User-Agent ->>+ OneIdentity: User landed on OneIdentity Login page
    end