sequenceDiagram
    participant User-Agent
    participant ARC
    participant OneIdentity as One Identity

    User-Agent ->> ARC: Invoke protected API
    ARC ->> ARC: Check if the token is valid
    alt Token Valid
        ARC -->> User-Agent: Access granted return resource
    else Token Invalid
        ARC ->>+ OneIdentity: Login required
        OneIdentity ->> OneIdentity: Execute authentication (stateless)
        OneIdentity -->>- ARC: Authenticated
        ARC ->> ARC: Generate new Access token
        ARC -->> User-Agent: Return new Access token
    end