sequenceDiagram
    actor Operatore
    participant UserAgent
    participant FE as FE_MyOperatore
    participant BFF as BFF_MyOperatore

    note over Operatore, UserAgent: Esegue la login e completa<BR />con successo l'autenticazione
    Operatore ->> UserAgent: 

    activate UserAgent
    note right of UserAgent: Viene reindirizzato verso la pagina<BR />di accettazione del token di login
    UserAgent ->> FE: GET /logged?login_token=<logintoken>
    activate FE
    FE ->> BFF: POST /public/authtoken

    activate BFF
    BFF -->> FE: access token JWT
    deactivate BFF

    FE -->> UserAgent: access token JWT
    deactivate FE
    alt L'operatore aveva spuntato la casella "Ricordami"
        note right of UserAgent: token di sessione persistito:<BR />Può essere o local storage o cookie,<BR />dipende da una configurazione del BFF
    else
        note right of UserAgent: token di sessione mantenuto in RAM
    end
    UserAgent -->> Operatore: 
    deactivate UserAgent