sequenceDiagram
    actor Operatore
    participant UserAgent
    participant FE as FE_MyOperatore
    participant BFF as BFF_MyOperatore
    participant MyId

    note right of Operatore: Utente privo di sessione valida
    Operatore ->> UserAgent: Accede ad una qualsiasi pagina
    activate UserAgent
    UserAgent ->> FE: #
    activate FE
    FE ->> UserAgent: Redirect verso pagina di login
    deactivate FE

    UserAgent ->> BFF: GET /saml/login?callbackUrl=<FE_BASE_URL>/logged
    activate BFF
    rect rgb(190, 190, 190)
    note right of MyId: Presente solo su YourPay
    BFF -->> UserAgent: Redirect verso servizio di autenticazione (protocollo SAML)
    deactivate BFF

    UserAgent ->> MyId: AuthnRequest
    activate MyId
    note right of MyId: L'utente si autentica
    MyId -->> UserAgent: Redirect con asserzione SAML
    deactivate MyId

    UserAgent ->> BFF: Consegna asserzione SAML
    activate BFF
    note right of BFF: Valida asserzione
    note right of BFF: Costruisce ID token
    BFF -->> UserAgent: Redirect verso pagina del FE per accettazione ID token
    deactivate BFF
    end

    UserAgent ->> FE: GET /logged?login_token=<ID Token>
    activate FE

    FE ->> BFF: POST /public/authtoken
    note over FE, BFF: ID Token passato come Body
    activate BFF
    note right of BFF: valida ID token
    BFF ->> BFF: upsert mygov_utente
    BFF ->> BFF: upsert mygov_operatore
    BFF -->> FE: access token JWT
    deactivate BFF

    FE -->> UserAgent: access token JWT
    deactivate FE
    alt L'operatore aveva spuntato la casella "Ricordami"
    note right of UserAgent: token di sessione persistito:<BR />Può essere o local storage o cookie,<BR />dipende da una configurazione del BFF
    else
    note right of UserAgent: token di sessione mantenuto in RAM
    end
    UserAgent -->> Operatore: #
    deactivate UserAgent
    note right of Operatore: Operatore libero di navigare<BR />all'interno del portale

Operatore ->> UserAgent: Naviga il portale

activate UserAgent
UserAgent ->> FE: #
activate FE
FE ->> BFF: Invoca API protetta
note over FE, BFF: Authorization: Bearer <accessToken>

activate BFF
BFF ->> AUTH: GET /tokeninfo
activate AUTH
alt token valido
AUTH -->> BFF: Claim interne al token
note right of BFF: Richiesta autorizzata<BR />Processa richiesta
else
AUTH -->> BFF: Forbidden
end
deactivate AUTH

activate AUTH
deactivate AUTH

BFF -->> FE: Esito richiesta
deactivate BFF

FE -->> UserAgent: Renderizza esito API
deactivate FE
UserAgent -->> Operatore: #
deactivate UserAgent
