sequenceDiagram
    actor Operatore
    participant UserAgent
    participant FE as FE_MyOperatore
    participant BFF as BFF_MyOperatore
    participant AUTH as Authorization Server

    Operatore ->> UserAgent: Accede al portale MyPay Operatore

    activate UserAgent
    note over Operatore, UserAgent: Privo di sessione valida
    UserAgent ->> FE: 
    activate FE
    FE -->> UserAgent: Redirect verso pagina di login
    deactivate FE

    UserAgent ->> BFF: Pagina di login
    activate BFF
    BFF -->> UserAgent: Redirect verso pagina di login
    deactivate BFF

    note over AUTH: Dal punto di vista di MyPay Operatore,<BR />si tratta di una sola entità.<BR />In realtà è qui che avverrà l'integrazione<BR />tra p4pa-auth e SelfCare
    UserAgent ->> AUTH: Pagina di login
    activate AUTH
    note right of AUTH: L'utente si autentica
    note right of AUTH: Generazione e salvataggio<BR />AuthenticationCode e ID Token
    AUTH -->> UserAgent: Redirect verso pagina di accettazione AuthenticationCode
    deactivate AUTH

    UserAgent ->> FE: Consegna AuthenticationCode
    activate FE
    FE ->> BFF: Consegna AuthenticationCode
    activate BFF
    BFF ->> AUTH: Consegna AuthenticationCode
    
    activate AUTH
    AUTH -->> BFF: ID Token
    deactivate AUTH

    BFF ->> AUTH: Recupera .well-known/jwks.json
    note right of BFF: Validazione ID Token<BR />e generazione access token
    BFF -->> FE: Access token
    deactivate BFF
    FE -->> UserAgent: 
    alt L'operatore ha spuntato la casella "Ricordami"
        note right of UserAgent: token di sessione persistito nel local storage
    else
    note right of UserAgent: token di sessione mantenuto in RAM
    end
    deactivate FE

    UserAgent -->> Operatore: 
    deactivate UserAgent
    
    note over Operatore, UserAgent: Da adesso l'operatore potrà navigare le pagine del FE