sequenceDiagram
    actor Operatore
    participant UserAgent
    participant FE as FE_MyOperatore
    participant BFF as BFF_MyOperatore
    participant AUTH as P4PA_AUTH
    participant SelfCare
    participant Redis


    activate UserAgent
    alt Operatore entra direttamente sul portale MyPay Operatore
        note over Operatore, UserAgent: Assenza di una sessione valida
        Operatore ->> UserAgent: Accede al portale MyPay Operatore

        UserAgent ->> FE: #
        activate FE
            FE -->> UserAgent: Redirect verso pagina di login
        deactivate FE
    else
        Operatore ->> UserAgent: Accede al portale SelfCare
    end

    UserAgent ->> SelfCare: Pagina di login
    activate SelfCare
        note right of SelfCare: L'utente si autentica e accede<br />al prodotto "Piattaforma Unitaria"
        SelfCare -->> UserAgent: Redirect verso pagina di accettazione ID Token
    deactivate SelfCare
    note over UserAgent, SelfCare: RFC 8693 dello standard OAuth 2.0, token passato mediante query param

    UserAgent ->> FE: GET /logged?login_token=<ID Token>
    activate FE
        FE ->> BFF: POST /public/authtoken Body:ID Token
        activate BFF
            BFF ->> AUTH: GET /authorize
            activate AUTH
                AUTH ->> SelfCare: Recupera .well-known/jwks.json
                note right of AUTH: Valida ID Token
                note right of AUTH: Genera access Token
                AUTH ->> BFF: Consegna access Token
            deactivate AUTH

            BFF ->> AUTH: GET /userinfo
            activate AUTH
                AUTH ->> SelfCare: getInstitutionProductOperatores
                note over AUTH, SelfCare: recupero email
                AUTH -->> BFF: Dati utente
            deactivate AUTH

            BFF ->> BFF: upsert mygov_utente
            BFF ->> BFF: upsert mygov_operatore
            BFF -->> FE: access token JWT
        deactivate BFF
        FE -->> UserAgent: #
        alt L'operatore ha spuntato la casella "Ricordami"
            note right of UserAgent: token di sessione persistito nel local storage
        else
            note right of UserAgent: token di sessione mantenuto in RAM
        end
    deactivate FE

    UserAgent -->> Operatore: #
    deactivate UserAgent

    note right of Operatore: Operatore libero di navigare<BR />all'interno del portale

    Operatore ->> UserAgent: Naviga il portale

    activate UserAgent
    UserAgent ->> FE: #
    activate FE
    FE ->> BFF: Invoca API protetta
    note over FE, BFF: Authorization: Bearer <accessToken>

    activate BFF
    BFF ->> AUTH: GET /userinfo
    activate AUTH
    alt token valido
        AUTH -->> BFF: Dati utente
        note right of BFF: Richiesta autorizzata<BR />Processa richiesta
    else
        AUTH -->> BFF: Forbidden
    end
    deactivate AUTH

    activate AUTH
    deactivate AUTH

    BFF -->> FE: Esito richiesta
    deactivate BFF

    FE -->> UserAgent: Renderizza esito API
    deactivate FE
    UserAgent -->> Operatore: #
    deactivate UserAgent