sequenceDiagram
    actor Operatore
    participant UserAgent
    participant FE as FE_MyOperatore
    participant BFF as BFF_MyOperatore
    participant AUTH as P4PA_AUTH
    participant SelfCare
    participant Redis


    activate UserAgent
    alt Operatore entra direttamente sul portale MyPay Operatore
    note over Operatore, UserAgent: Assenza di una sessione valida
    Operatore ->> UserAgent: Accede al portale MyPay Operatore

    UserAgent ->> FE: #
    activate FE
    FE -->> UserAgent: Redirect verso pagina di login
    deactivate FE

    UserAgent ->> BFF: Pagina di login
    activate BFF
    BFF -->> UserAgent: Redirect verso servizio di autenticazione
    deactivate BFF
    else
    Operatore ->> UserAgent: Accede al portale SelfCare
    end

    UserAgent ->> SelfCare: Pagina di login
    activate SelfCare
    note right of SelfCare: L'utente si autentica e accede<br />al prodotto "Piattaforma Unitaria"
    SelfCare -->> UserAgent: Redirect verso pagina di accettazione tokenExchange
    note over UserAgent, SelfCare: RFC 8693 dello standard OAuth 2.0, token passato mediante fragment
    deactivate SelfCare

    UserAgent ->> AUTH: GET /payhub/auth?token=<tokenExchange>
    activate AUTH
    AUTH ->> SelfCare: Recupera .well-known/jwks.json
    note right of AUTH: Valida tokenExchange
    AUTH ->> SelfCare: getInstitutionProductOperatores
    note over AUTH, SelfCare: recupero email
    note right of AUTH: Genera ID token
    AUTH ->> Redis: Genera una nuova chiave (Authorization Code)<BR />e salva contestualmente l'ID token settando una TTL
    AUTH -->> UserAgent: Redirect verso pagina di accettazione Authorization Code
    deactivate AUTH

    UserAgent ->> FE: Consegna Authorization Code
    activate FE
    FE ->> BFF: Consegna Authorization Code
    activate BFF
    BFF ->> AUTH: Consegna Authorization Code

    activate AUTH
    AUTH ->> Redis: Recupero ID Token
    alt ID Token trovato
    AUTH -->> BFF: ID Token
    deactivate AUTH

    BFF ->> AUTH: Recupera .well-known/jwks.json
    note right of BFF: Valida ID Token e genera access token
    BFF -->> FE: access token JWT
    deactivate BFF
    FE -->> UserAgent: #
    alt L'operatore ha spuntato la casella "Ricordami"
    note right of UserAgent: token di sessione persistito nel local storage
    else
    note right of UserAgent: token di sessione mantenuto in RAM
    end
    else
    AUTH -->> BFF: Unauthorized
    BFF -->> FE: Redirect pagina di login
    end
    deactivate FE

    UserAgent -->> Operatore: #
    deactivate UserAgent

    note over Operatore, UserAgent: Da adesso l'operatore potrà navigare le pagine del FE